name: laravel-create-project

on:
  pull_request:
  schedule:
    - cron:  '0 0 * * *'

jobs:
  docker-build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Docker Compose Version
        run: docker-compose --version

      - name: Build Docker
        run: docker-compose build

      - name: Start Docker
        run: docker-compose up -d

      - name: Create Laravel Project
        run: docker-compose exec -T app composer create-project --prefer-dist laravel/laravel .

      - name: PHP Version
        run: docker-compose exec -T app php --version

      - name: Composer Version
        run: docker-compose exec -T app composer --version

      - name: Laravel Version
        run: docker-compose exec -T app php artisan --version

      - name: Laravel Migrate Testing
        run: docker-compose exec -T app php artisan migrate

      - name: Laravel Rollback Testing
        run: docker-compose exec -T app php artisan migrate:refresh --seed

      - name: Laravel Seeding Testing
        run: docker-compose exec -T app php artisan db:seed

      - name: Laravel PHPUnit Testing
        run: docker-compose exec -T app php artisan test
